### PR TITLE
fix: disable proxy buffering and cache

### PR DESCRIPTION
**Pull request by nityanandagohain**
This is for fixing live tail issue

### CODE REVIEW

**Review by prashant-shahi — APPROVED** [review]

**Comment by srikanthccv** [comment]
@nityanandagohain please do not disable it for everything unless you have good reason. Just limit it to the live tail. 

> There are only a small number of use cases where disabling proxy buffering might make sense (such as long polling), so we strongly discourage changing the default

https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/#proxy_buffering-off

**Comment by prashant-shahi** [comment]
@nityanandagohain Try this:

```
location ~ ^/api/(v1|v3)/logs/(livetail|tail) {
   ...

   proxy_pass http://{{ include "queryService.url" . }};
}
```

**Comment by prashant-shahi** [comment]
> @nityanandagohain please do not disable it for everything unless you have good reason. Just limit it to the live tail.

@srikanthccv what would be the reasons for `strongly discouraging`? Is it due to increase in response time due to cache disabling? And the no buffer in Nginx, causing data to be sent directly to client in chunks? Won't the data be up-to-dated that way and data latency minimised?

I see both pros and cons of disabling them in general.

How does these affect the other SigNoz backend APIs?

**Comment by srikanthccv** [comment]
> Is it due to increase in response time due to cache disabling?

Yes, as mentioned in the nginx doc, cache won't be effective when you disable buffering.

> And the no buffer in Nginx, causing data to be sent directly to client in chunks? Won't the data be up-to-dated that way and data latency minimised?

If you are optimising for the TTFB then it makes sense otherwise by enabling the buffering, we free up the backend and let the nginx take care of the client. This means the backend can go ahead and serve another request without worrying about how fast the client can read the data stream and the latency difference observed by directly sending to the client is usually negligible.

**Pull request merged**
