### PR TITLE
FIX: Alertmanager - Add arg cluster.advertise-address at all times

### PR DESCRIPTION
**Pull request by mknapcok**
With single replica of Alertmanager it is failing to start without argument --cluster.advertise-address=$(POD_IP):{{ $svcClusterPort }}

More info: https://github.com/SigNoz/charts/issues/283

### CODE REVIEW

**Comment by prashant-shahi** [comment]
@mknapcok Thanks for raising the PR.

I am looking into it. Verifying the reported issue first.

**Comment by prashant-shahi** [comment]
@mknapcok can you please bump up the signoz chart version?
That should trigger a chart release when PR is merged.

**Review by prashant-shahi — APPROVED** [review]
LGTM

**Comment by mknapcok** [comment]
Good to merge? @prashant-shahi

**Comment by prashant-shahi** [comment]
@mknapcok yes, it is merged and released.
Thanks for the PR fix.

**Pull request merged**
