### PR TITLE
Add spanmetrics processor delta pipeline

### PR DESCRIPTION
**Pull request by srikanthccv**
Part of https://github.com/SigNoz/signoz/issues/3579

- The scraping approach has several issues namely
   - broken pipe error, this happens when the amount of data is large but the request times out https://github.com/SigNoz/signoz-otel-collector/issues/179
   - the stale time series are kept in memory till the process restart
   - can only use cumulative because Prometheus only supports it.

In this collector PR https://github.com/SigNoz/signoz-otel-collector/pull/201, the need for depending on Prometheus is removed and we can use clickhousemetrics exporter directly. 

This PR does two things

1. Remove the Prometheus dependency for span metrics
2. Add delta span metrics to the pipeline

What works today will continue to work. There will be separate time series data for delta span metrics. We will continue to keep both cumulative for 1 month. Once the month (ttl) amount of data gets backfilled, we enable the prefer-delta by default for everyone and remove the cumulative pipeline.

### CODE REVIEW

**Comment by srikanthccv** [comment]
Review please

**Comment by ankitnayan** [comment]
@prashant-shahi please review.

Are the `relabel_configs` not needed anymore?

**Comment by srikanthccv** [comment]
The `__meta_kubernetes_pod*` was never useful (and removed in saas already) because they will be populated with the collector pod details where the metrics are collected from (nothing outside our collector pods emits the span metrics). 

The `__meta_kubernetes_pod_annotation_apm_*` are instructions to keep the span metrics and drop any other scraped metrics.

**Comment by ankitnayan** [comment]
okay...and where is the `collector_id` stored? I remember we had that to give correct APM data. That `collector_id` won't be needed in delta temporality, right?

**Comment by srikanthccv** [comment]
It is part of main collector `dimensions:` [config](https://github.com/SigNoz/charts/pull/355/files#diff-69ae60f6e74067370d36c6fb708091d276d8b72457de434d4e2f91c0c180ba9aL1690). Yes, it is not needed for delta. When we move the delta completely we can get rid of it meanwhile it can exist.

**Comment by ankitnayan** [comment]
Nice. I am expecting delta temporality to be faster and memory efficient as well since we do not hold the data anymore. I would recommend testing before making live

**Comment by ankitnayan** [comment]
also, the `Test Charts` seem to be failing

**Comment by srikanthccv** [comment]
Yes, there are several benefits, it will be faster, accurate (no need to worry about resets), memory efficient, enables moving the span metrics collection to gw collector, and other things I can't think of now.

I tested from my side and want make sure this change must not break anything. If you look at the current saas span metrics config the only thing you see is [config](https://github.com/SigNoz/charts-saas-v2/blob/2ba7a22d0d6545a5e743a1700d71ebf2023ab9ac/charts/signoz/values-gokiwi.yaml#L101-L114) that lets the scrper know the `host:port` of the pod to scrape. And the rest is just writing scraped data as is. That will be continued with the cumulative pipeline. And we add a new pipeline for delta. Since we added the temporality to the label set the fingerprint will be different for cumulative and delta. When this is fine from reviewers side I will make it run on parallel test instance of customer and ensure. 

The failed job is not related to changes. It has been failing on all PRs for quite some time.

**Comment by srikanthccv** [comment]
I tested this on the docker setup long back https://github.com/SigNoz/signoz/pull/3776 and this PR on kind cluser setup locally. I am confident we are not missing anything but I will double check anyway.

**Comment by prashant-shahi** [comment]
>  Are the `relabel_configs` not needed anymore?

They mainly helped to know which metics were created by which otelcol pod or k8s node. But I don't think anything beyond that.

Since we will now be sending metrics directly from signozspanmetrics processor to metrics exporter, I don't think there is any need for involvement of prometheus or the `relabel_configs`.

**Comment by prashant-shahi** [comment]
@srikanthccv can you also remove `apm.signoz.io` pod annotations from `values.yaml`?

**Review by prashant-shahi — APPROVED** [review]

**Pull request merged**
