### PR TITLE
fix: remove default trace_parser

### PR DESCRIPTION
**Pull request by nityanandagohain**
It's better to show how to create one in pipelines and then add a default one (disabled) in the pipelines which user can modify according to requirements.

### CODE REVIEW

**Comment by srikanthccv** [comment]
For the existing users who relied on this default parser either knowingly or unknowingly, this will be a breaking change and it suddenly stops working for them. That doesn't seem like a good default to me. What do we do about them? Is there an alternative that doesn't require deleting the default parser?

**Comment by nityanandagohain** [comment]
The trace parser was not in a working state and it was brough to a wroking state with this PR https://github.com/SigNoz/charts/commit/7327a29e8184feda117d0bd374f65a3a9de61465 , so I think we can remove this and won't cause users any issues, if someone faces any problem we can share the doc and they can set it up quicky.

It's better to remove it now then removing it in the future.

**Review by srikanthccv — APPROVED** [review]

**Comment by srikanthccv** [comment]
Fix the tests and merge

**Comment by nityanandagohain** [comment]
Have tested it locally merging it. cc @prashant-shahi

**Comment by prashant-shahi** [comment]
There is a known issue but it only happens when changes of multiple charts are added in single PR and multiple chart tests are run.

Issue: https://github.com/helm/chart-testing/issues/587

But here the change is specific to one chart, it shouldn't have run tests for all charts.
Looking into it.

For now, locally testing should be enough.

**Review by prashant-shahi — APPROVED** [review]

**Comment by srikanthccv** [comment]
I still find not having a default trace parser is not a good default choice. If it had some conflicts with pipeline preview we need to find a solution. And if it didn't work we should make it work. I believe the trace parser should be enabled by default.

**Pull request merged**
