### PR TITLE
feat(helm): ✨ otel collector and metric templates and other changes

### PR DESCRIPTION
**Pull request by prashant-shahi**
- add templates for otel collector and otel collector metrics
- single helper file for basic templates 
- single valid notes.txt 
- alertmanager api from env var

Signed-off-by: Prashant Shahi <prashant@signoz.io>

### CODE REVIEW

**Comment by ankitnayan** [comment]
@prashant-shahi Is it tested?

**Comment by prashant-shahi** [comment]
yes, it is tested manually.. and also CI lint and test passed

**Comment by ankitnayan** [comment]
Cool :+1:

**Review by ankitnayan — APPROVED** [review]

**Comment by prashant-shahi** [comment]
This is part of helm chart release [signoz-0.0.6](https://github.com/SigNoz/charts/releases/tag/signoz-0.0.6).

@pranay01 requesting for shipped love..

**Pull request merged**
