### PR TITLE
Move to attributes instead of resources.

### PR DESCRIPTION
**Pull request by nityanandagohain**
The k8sattribute processor adds to attributes by default, so it can override this and there will be no duplicates.

### CODE REVIEW

**Review by prashant-shahi — APPROVED** [review]

**Comment by prashant-shahi** [comment]
@nityanandagohain LGTM.

However, I wasn't able to see any duplicates issue prior to these changes.

**Comment by nityanandagohain** [comment]
@prashant-shahi it doesn't appear as duplicate, but when you create a selected field out of it a conflict arises.

**Comment by nityanandagohain** [comment]
Sorry I didn't get you @srikanthccv .

This PR leaves the k8s attribute extraction part to the processor and remove any custom extraction that we have added.

**Comment by srikanthccv** [comment]
This moves from the resource to attributes, and now, there are two places where `k8s.*` attributes are available, the log record attributes and log resource attributes. I was saying, why not let the processor only add the `k8s` attributes to a resource? Why add them to log record attributes when it is semantically incorrect to add `k8s` attributes to the log record?

**Comment by srikanthccv** [comment]
This also makes fields appear twice on selected/interesting fields since they exist in both the resource and attributes. Please test what happens when you try to add/remove such fields from the UI and its behaviour on ClickHouse column manipulation.

**Comment by nityanandagohain** [comment]
Right @srikanthccv , so this PR does exactly that.

But there is a catch to it.

the k8s attribute processor adds the attributes to the `attributes` map instead of `resources` map. 

The goal of this PR:- 
* Extract whatever whatever we can to attributes
* If the user doesn't use k8sattributes processor this will be present.
* If they use the processor these will be overridden.

**Comment by srikanthccv** [comment]
>the k8s attribute processor adds the attributes to the attributes map instead of resources map.

This is not true AFAIK, Where does it do this _adds the attributes to the attributes map instead of resources map_

**Comment by srikanthccv** [comment]
It's not true, and you can confirm this by running the setup locally. The `k8s` attributes should go in the resource attributes.

**Comment by srikanthccv** [comment]
Screenshot 2023-01-31 at 2 29 36 PM

**Comment by nityanandagohain** [comment]
Getting back to you on this @srikanthccv

**Comment by nityanandagohain** [comment]
You are right Srikanth, When I tested it for one of the user at that point in time removing it from the resources solved the issue. But should have dug deeper.


Reverting this change.

**Pull request merged**
