### PR TITLE
Release/signoz 0.11.3

### PR DESCRIPTION
**Pull request by srikanthccv**
Update query-service/frontend version to v0.16.2 and collector to 0.66.5

### CODE REVIEW

**Comment by prashant-shahi** [comment]
@srikanthccv can you also bump up versions of K8s-Infra collectors to `0.70.0`?

I know it might seem redundant to have those values in two place. In coming days, we will cleanup and remove redundant values from K8s-Infra chart in SigNoz chart since they will be default.

For now, could you please make sure the changes in `values.yaml` of K8s-Infra chart from two release versions are synced in `values.yaml` of SigNoz?

https://github.com/SigNoz/charts/compare/k8s-infra-0.6.5...k8s-infra-0.7.0#diff-59749a6a176adc33824cd6adda9545ee3cf7c3163749655ce9f81745281968ac

**Comment by srikanthccv** [comment]
@prashant-shahi, made the requested changes, please take another look.

**Review by prashant-shahi — APPROVED** [review]
LGTM :shipit:

**Comment by prashant-shahi** [comment]
@srikanthccv Good to merge after the chart test passes.

**Comment by srikanthccv** [comment]
Tested the latest changes 
Screenshot 2023-02-25 at 2 21 45 AM
Screenshot 2023-02-25 at 2 22 39 AM

**Comment by srikanthccv** [comment]
Thanks for the review. Merging.

**Comment by prashant-shahi** [comment]
@srikanthccv Happy to be there on the other side, reviewing.

I am also glad to see you do a nice job with the release of SigNoz, SigNoz OtelCollector and signoz chart. :partying_face: :confetti_ball:

**Pull request merged**
