### PR TITLE
Release/k8s infra 0.8.2

### PR DESCRIPTION
**Pull request by prashant-shahi**
Signed-off-by: Prashant Shahi <prashant@signoz.io>

### CODE REVIEW

**Comment by srikanthccv** [comment]
It would be a good idea to do this after the `0.19` release since there are some breaking changes.

**Comment by prashant-shahi** [comment]
@srikanthccv haven't we synced our collector with v0.76.x? won't that cause any breaking changes for signoz-otel-collector?

**Comment by srikanthccv** [comment]
>haven't we synced our collector with v0.76.x? won't that cause any breaking changes for signoz-otel-collector?

sync with what? not sure what you are trying to say here. We didn't want to update the collector version in the charts until the release happened on the SigNoz/signoz repo and then update the collector version along with the frontend and query-service.

**Comment by prashant-shahi** [comment]
SigNoz/signoz repo was out prior to this PR. This PR is mainly for bumping up K8s-Infra collectors.
Anyways, chart release is out now without this change.

Let me know when this can go out.

**Comment by srikanthccv** [comment]
I think it wasn't published yet by the time I made that comment because I wanted to do basic testing, and it didn't succeed with pulling images. We could get this anytime out. Also, I was hoping to see resources updated similar the to reflect the core repo changes in https://github.com/SigNoz/charts/pull/228.

**Comment by srikanthccv** [comment]
See this https://github.com/SigNoz/charts/pull/231. You can publish 0.15.1 or something now.

**Comment by prashant-shahi** [comment]
> See this https://github.com/SigNoz/charts/pull/231. You can publish 0.15.1 or something now.

reviewed and merged. yes, we can go out with 0.15.1 after this PR gets merged.

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
